import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BaseitemComponent } from '../_component/baseitem/baseitem.component';

@Component({
  selector: 'app-gridflex-control',
  standalone: true,
  imports: [CommonModule, BaseitemComponent],
  templateUrl: './gridflex-control.component.html',
  styleUrls: ['./gridflex-control.component.css']
})
export class GridflexControlComponent {
  getCellClasses(rowIdx: number, colIdx: number): string {
    const baseClass = `cell-${rowIdx}-${colIdx}`;
    const evenOddClass = (rowIdx + colIdx) % 2 === 0 ? 'even-cell' : 'odd-cell';
    return `${baseClass} ${evenOddClass}`;
  }
  readonly gridComponents = [
    {
      id: 'CS_TOKCD',
      type: 'button',
      displayName: 'TOKCD',
      width: 5,
      height: 1,
      row: 2,
      col: 2,
      gridrow: 0,
      gridcol: 0,
    },
    {
      id: 'HD_TOKCD',
      type: 'input',                   
      displayName: 'TOKCD',
      width: 7,
      height: 1,
      row: 2,
      col: 7,
      gridrow: 0,
      gridcol: 0,
    },
    {
      id: 'LBL_TOK',
      type: 'label',                   
      displayName: 'NAME',
      width: 4,
      height: 2,
      row: 3,
      col: 2,
      gridrow: 0,
      gridcol: 0,
    },
    {
      id: 'HD_TOKNM',
      type: 'input',                   
      displayName: 'TOKNM',
      width: 15,
      height: 1,
      row: 3,
      col: 6,
      gridrow: 0,
      gridcol: 0,
    },
    {
      id: 'HD_TOKRN',
      type: 'input',                   
      displayName: 'TOKRN',
      width: 10,
      height: 1,
      row: 4,
      col: 6,
      gridrow: 0,
      gridcol: 0,
    },
    {
      id: 'CS_DENCM',
      type: 'button',
      displayName: 'DENCM',
      width: 5,
      height: 3,
      row: 2,
      col: 2,
      gridrow: 0,
      gridcol: 1,
    },
    {
      id: 'HD_DENCM',
      type: 'input',
      displayName: 'DENCM',
      width: 12,
      height: 1,
      row: 2,
      col: 7,
      gridrow: 0,
      gridcol: 1,
    },
    {
      id: 'HD_DENCMB',
      type: 'input',
      displayName: 'DENCMB',
      width: 12,
      height: 1,
      row: 3,
      col: 7,
      gridrow: 0,
      gridcol: 1,
    },
    {
      id: 'HD_DENCMC',
      type: 'input',
      displayName: 'DENCMC',
      width: 12,
      height: 1,
      row: 4,
      col: 7,
      gridrow: 0,
      gridcol: 1,
    },
    {
      id: 'LBL_LINCM',
      type: 'label',
      displayName: 'LINCM',
      width: 5,
      height: 3,
      row: 2,
      col: 2,
      gridrow: 1,
      gridcol: 1,
    },
    {
      id: 'HD_LINCMA',
      type: 'input',
      displayName: 'LINCMA',
      width: 12,
      height: 1,
      row: 2,
      col: 7,
      gridrow: 1,
      gridcol: 1,
    },
    {
      id: 'HD_LINCMB',
      type: 'input',
      displayName: 'LINCMB',
      width: 12,
      height: 1,
      row: 3,
      col: 7,
      gridrow: 1,
      gridcol: 1,
    },
    {
      id: 'HD_LINCMC',
      type: 'input',
      displayName: 'LINCMC',
      width: 12,
      height: 1,
      row: 4,
      col: 7,
      gridrow: 1,
      gridcol: 1,
    }
  ];
}
